# Generated by Django 4.2.30 on 2026-07-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0231_alter_badge_full_size_alter_badge_mini'),
        ('judge', '0231_contest_replay_version'),
    ]

    operations = [
    ]
